[templates]
directory = "./templates"

[assets.directories]
"assets" = "./assets"
"src" = "./src"

[assets.files]
"assets/htmx.min.js" = "../node_modules/htmx.org/dist/htmx.min.js"
"assets/react-day-picker.css" = "../node_modules/react-day-picker/src/style.css"

