[package]
name = "TJ2"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"

[dependencies.toml]
version = "0.8"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.thiserror]
version = "1"

[dependencies.sha2]
version = "0.10"

[dependencies.sha3]
version = "0.10"

[dependencies.tokio]
version = "1"
features = ["signal", "time", "rt-multi-thread", "net", "fs", "tracing"]

[dependencies.axum]
version = "0.7"

[dependencies.hyper]
version = "1"

